# Generated by Django 5.2.4 on 2025-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Estudiante"),
                    ("teacher", "Maestro"),
                    ("admin", "Administrador"),
                    ("preu", "Preuniversitario"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
